services:
  - type: web
    name: financial-health-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flask_backend:app
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.12"
      - key: FLASK_ENV
        value: "production"
      - key: PYTHONUNBUFFERED
        value: "1"
    autoDeploy: true
    branch: main
